### ISSUE TITLE
Time measurement

### ISSUE THREAD

**Issue by alexander-schranz** [php-task/TaskBundle#11]
When a task is completed it would also be a good information how long the task did take to run.

**Comment by wachterjohannes** [comment]
maybe an `afterRun` hook with the time and memory information. should also be saved in the database

**Comment by wachterjohannes** [comment]
should be fixed with https://github.com/php-task/TaskBundle/blob/master/src/Resources/config/doctrine/TaskExecution.orm.xml#L20
