### ISSUE TITLE
Compatible with SF4

### ISSUE THREAD

**Issue by faysh** [php-task/TaskBundle#46]
Hello. Thank you for great bundle.
We used your bundle for a long time, but after updating our project to symfony 4, unfortunately it don't compatible with more required dependencies of your bundle.
I want to know will you upgrade your bundle for compatibility with sf4 in near future?
Best regards, Shuhrat

**Comment by wachterjohannes** [comment]
@faysh would you like to test this? https://github.com/php-task/TaskBundle/pull/47 I have no idea in which version I will release this (is a small BC-break but it is one) - maybe I will go with 1.3
