### ISSUE TITLE
Cant use schema update when have tagged services

### ISSUE THREAD

**Issue by alexander-schranz** [php-task/TaskBundle#8]
If you have exist `task.interval` tagged services you can't run `app/console doctrine:schema:update` to create the tasks tables.

SQL to create it manually:

```sql
CREATE TABLE `tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `task` longtext COLLATE utf8_unicode_ci NOT NULL COMMENT '(DC2Type:object)',
  `uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `executionDate` datetime NOT NULL,
  `completed` tinyint(1) NOT NULL,
  `task_key` varchar(255) COLLATE utf8_unicode_ci DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by wachterjohannes** [comment]
hmm do you have any idea how to fix it?

**Comment by alexander-schranz** [comment]
I think I would add a try and catch and LOG an error?

**Comment by wachterjohannes** [comment]
we should debug this next week the question is why is this called when you update the schema.

**Comment by wachterjohannes** [comment]
The current update removes the tags so we can close this issue
